version: '3.8'

services:
    mymbafeeder:
        image: mymbafeeder:0.1
        restart: always
        container_name: mymbafeeder
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - 5000:5000
        depends_on: 
            - mongo
        command: python app.py
    
    mongo:
        image: mongo
        restart: always
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: root    #db username
            MONGO_INITDB_ROOT_PASSWORD: example #db password
        volumes: 
            - ./mongodata:/data/db
    
    mongo-express:
        image: mongo-express
        restart: always
        container_name: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb           # mongo service container name
            ME_CONFIG_MONGODB_ADMINUSERNAME: root       # db mongo username
            ME_CONFIG_MONGODB_ADMINPASSWORD: example    # db mongo passw
            ME_CONFIG_BASICAUTH_USERNAME: admin         # mongo-express login user
            ME_CONFIG_BASICAUTH_PASSWORD: admin         # mongo-empress login passw
        depends_on: 
            - mongo

# runs on docker-compose up --build -d